### get token directly from service (and save)
POST http://localhost:8084/token
Content-Type: application/json

{}
> {%
    client.global.set('auth_token', response.body.access_token)
%}

### get token from gateway (and save)
POST http://localhost:8080/auth/token
Content-Type: application/json

> {%
    client.global.set('auth_token', response.body.access_token)
%}

### get list of oauth servers
GET http://localhost:8081/oauth/servers
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### get example (no need Authorization)
GET http://localhost:8080/example
Content-Type: application/json

### get exampleauth (need Authorization)
GET http://localhost:8080/example
Content-Type: application/json
Authorization: Bearer {{auth_token}}