### get example-basic -> service[x]/ (Hello World!)
GET http://localhost:80/example-basic
Content-Type: application/json

### get example-basic/zosia/marysia -> service[x]/zosia/marysia (fake)
GET http://localhost:80/example-basic/zosia/marysia
Content-Type: application/json