### get token directly from service (and save)
POST http://localhost:8084/token
Content-Type: application/json

{}
> {%
    client.global.set('auth_token', response.body.access_token)
%}

### get token from gateway (and save)
POST http://localhost:80/auth/token
Content-Type: application/json

{}
> {%
    client.global.set('auth_token', response.body.access_token)
%}

### fake logout
POST http://localhost:80/
Content-Type: application/json

> {%
    client.global.clear('auth_token')
%}

### get list of oauth servers
GET http://localhost:81/oauth/servers
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### get example-basic (no need Authorization)
GET http://localhost:80/example-basic
Content-Type: application/json

### get example-auth (need Authorization)
GET http://localhost:80/example-auth
Content-Type: application/json
Authorization: Bearer {{auth_token}}
