version: '3.8'
services:

  gateway:
    container_name: ${COMPOSE_PROJECT_NAME}_gateway
    build:
      context: gateway
      target: ${BUILD_TARGET}
    restart: on-failure
    ports:
      - "80:8080"
      - "81:8081"
    tty: true
    depends_on:
      - service1
      - service2
      - auth-service
    volumes:
      - ../etc/janus:/etc/janus
#    command: /app/janus start
    networks:
        devapp: ~

  auth-service:
    container_name: ${COMPOSE_PROJECT_NAME}_auth_service
    image: rodolpheche/wiremock
    ports:
      - '8084:8080'
    volumes:
      - ../stubs/auth:/home/wiremock/mappings
    networks:
      devapp: ~

  service1:
    container_name: ${COMPOSE_PROJECT_NAME}_service1
    image: mmalessa/go-dummy-http:1.0.1
    environment:
        - APP_INSTANCE=http1
    ports:
        - 8081:80
    networks:
        devapp: ~

  service2:
    container_name: ${COMPOSE_PROJECT_NAME}_service2
    image: mmalessa/go-dummy-http:1.0.1
    environment:
        - APP_INSTANCE=http2
    ports:
        - 8082:80
    networks:
        devapp: ~

networks:
    devapp:
        name: devapp